In [30]:

import pandas as pd
df=pd.read_excel(r"C:\Users\Dell\Desktop\DATA12.xlsx")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth,Salary
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,0.30,NaN
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,NaN,NaN
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,NaN,NaN
3,4.0,NaN,IT Services,2013.0,NaN,"7,429,377 Dollars",6597557.0,NaN,NaN
4,5.0,NaN,NaN,NaN,NaN,"7,435,363 Dollars",3138627.0,NaN,NaN
5,6.0,Techline,Health,2006.0,NaN,"5,470,303 Dollars",8427816.0,0.23,NaN
6,7.0,Cityace,NaN,2010.0,"$9,254,614",NaN,3005116.0,0.06,NaN
7,8.0,Kayelectronics,NaN,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,0.04,NaN
8,9.0,Ganzlax,IT Services,2011.0,"$14,001,180",NaN,11901180.0,0.18,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         9 non-null      float64
 1   Name       7 non-null      object
 2   Industry   6 non-null      object
 3   Inception  8 non-null      float64
 4   Revenue    6 non-null      object
 5   Expenses   6 non-null      object
 6   Profit     9 non-null      float64
 7   Growth     5 non-null      float64
 8   Salary     0 non-null      float64
dtypes: float64(5), object(4)
memory usage: 848.0+ bytes

In [32]:
df.isnull().sum()

ID            1
Name          3
Industry      4
Inception     2
Revenue       4
Expenses      4
Profit        1
Growth        5
Salary       10
dtype: int64

In [5]:
df.isnull().sum()/len(df)

ID           0.1
Name         0.3
Industry     0.4
Inception    0.2
Revenue      0.4
Expenses     0.4
Profit       0.1
Growth       0.5
Salary       1.0
dtype: float64

In [6]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth,Salary
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,0.30,NaN
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,NaN,NaN
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,NaN,NaN
3,4.0,NaN,IT Services,2013.0,NaN,"7,429,377 Dollars",6597557.0,NaN,NaN
4,5.0,NaN,NaN,NaN,NaN,"7,435,363 Dollars",3138627.0,NaN,NaN
5,6.0,Techline,Health,2006.0,NaN,"5,470,303 Dollars",8427816.0,0.23,NaN
6,7.0,Cityace,NaN,2010.0,"$9,254,614",NaN,3005116.0,0.06,NaN
7,8.0,Kayelectronics,NaN,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,0.04,NaN
8,9.0,Ganzlax,IT Services,2011.0,"$14,001,180",NaN,11901180.0,0.18,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df.drop(['Salary'],axis=1,inplace=True)

In [34]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,NaN
3,4.0,NaN,IT Services,2013.0,NaN,"7,429,377 Dollars",6597557.0,NaN
4,5.0,NaN,NaN,NaN,NaN,"7,435,363 Dollars",3138627.0,NaN
5,6.0,Techline,Health,2006.0,NaN,"5,470,303 Dollars",8427816.0,0.23
6,7.0,Cityace,NaN,2010.0,"$9,254,614",NaN,3005116.0,0.06
7,8.0,Kayelectronics,NaN,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,"$14,001,180",NaN,11901180.0,0.18
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df.dropna(how='all',inplace=True)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,NaN
3,4.0,NaN,IT Services,2013.0,NaN,"7,429,377 Dollars",6597557.0,NaN
4,5.0,NaN,NaN,NaN,NaN,"7,435,363 Dollars",3138627.0,NaN
5,6.0,Techline,Health,2006.0,NaN,"5,470,303 Dollars",8427816.0,0.23
6,7.0,Cityace,NaN,2010.0,"$9,254,614",NaN,3005116.0,0.06
7,8.0,Kayelectronics,NaN,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,"$14,001,180",NaN,11901180.0,0.18

In [36]:
df.isnull().sum()/len(df)

ID           0.000000
Name         0.222222
Industry     0.333333
Inception    0.111111
Revenue      0.333333
Expenses     0.333333
Profit       0.000000
Growth       0.444444
dtype: float64

In [38]:
s=df['Revenue']
s

0    $11,757,018
1    $12,329,371
2    $10,597,009
3             NaN
4             NaN
5             NaN
6     $9,254,614
7     $9,451,943
8    $14,001,180
Name: Revenue, dtype: object

In [39]:
df['Revenue']=df['Revenue'].fillna(0)

In [40]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,NaN
3,4.0,NaN,IT Services,2013.0,0,"7,429,377 Dollars",6597557.0,NaN
4,5.0,NaN,NaN,NaN,0,"7,435,363 Dollars",3138627.0,NaN
5,6.0,Techline,Health,2006.0,0,"5,470,303 Dollars",8427816.0,0.23
6,7.0,Cityace,NaN,2010.0,"$9,254,614",NaN,3005116.0,0.06
7,8.0,Kayelectronics,NaN,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,"$14,001,180",NaN,11901180.0,0.18

In [41]:
p=df['Revenue']
p

0    $11,757,018
1    $12,329,371
2    $10,597,009
3               0
4               0
5               0
6     $9,254,614
7     $9,451,943
8    $14,001,180
Name: Revenue, dtype: object

In [46]:
r = []
for i in p:
    s = ""
    for j in str(i):
        if j.isdigit():
            s = s + j
    r.append(s)

r

['11757018',
 '12329371',
 '10597009',
 '0',
 '0',
 '0',
 '9254614',
 '9451943',
 '14001180']

In [47]:
df['Revenue']=r

In [48]:
df['Revenue']=df['Revenue'].astype('int')

In [49]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,11757018,"6,482,465 Dollars",5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,12329371,"916,455 Dollars",11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,10597009,NaN,3005820.0,NaN
3,4.0,NaN,IT Services,2013.0,0,"7,429,377 Dollars",6597557.0,NaN
4,5.0,NaN,NaN,NaN,0,"7,435,363 Dollars",3138627.0,NaN
5,6.0,Techline,Health,2006.0,0,"5,470,303 Dollars",8427816.0,0.23
6,7.0,Cityace,NaN,2010.0,9254614,NaN,3005116.0,0.06
7,8.0,Kayelectronics,NaN,2009.0,9451943,"3,878,113 Dollars",5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,14001180,NaN,11901180.0,0.18

In [50]:
h=df['Expenses']
h

0    6,482,465 Dollars
1      916,455 Dollars
2                  NaN
3    7,429,377 Dollars
4    7,435,363 Dollars
5    5,470,303 Dollars
6                  NaN
7    3,878,113 Dollars
8                  NaN
Name: Expenses, dtype: object

In [56]:
df['Expenses']=df['Expenses'].astype(0)

TypeError: Cannot interpret '0' as a data type

In [52]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,11757018,"6,482,465 Dollars",5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,12329371,"916,455 Dollars",11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,10597009,0,3005820.0,NaN
3,4.0,NaN,IT Services,2013.0,0,"7,429,377 Dollars",6597557.0,NaN
4,5.0,NaN,NaN,NaN,0,"7,435,363 Dollars",3138627.0,NaN
5,6.0,Techline,Health,2006.0,0,"5,470,303 Dollars",8427816.0,0.23
6,7.0,Cityace,NaN,2010.0,9254614,0,3005116.0,0.06
7,8.0,Kayelectronics,NaN,2009.0,9451943,"3,878,113 Dollars",5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,14001180,0,11901180.0,0.18

In [53]:
z=df['Expenses']
z

0    6,482,465 Dollars
1      916,455 Dollars
2                    0
3    7,429,377 Dollars
4    7,435,363 Dollars
5    5,470,303 Dollars
6                    0
7    3,878,113 Dollars
8                    0
Name: Expenses, dtype: object

In [57]:
r=[]
for i in z:
    s=''
    for j in str(i):
        if j.isdigit():
            s=s+j
    r.append(s)
r

['6482465',
 '916455',
 '0',
 '7429377',
 '7435363',
 '5470303',
 '0',
 '3878113',
 '0']

In [58]:
df['Expenses']=r

In [59]:
df['Expenses']=df['Expenses'].astype('int')

In [60]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,11757018,6482465,5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,12329371,916455,11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,10597009,0,3005820.0,NaN
3,4.0,NaN,IT Services,2013.0,0,7429377,6597557.0,NaN
4,5.0,NaN,NaN,NaN,0,7435363,3138627.0,NaN
5,6.0,Techline,Health,2006.0,0,5470303,8427816.0,0.23
6,7.0,Cityace,NaN,2010.0,9254614,0,3005116.0,0.06
7,8.0,Kayelectronics,NaN,2009.0,9451943,3878113,5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,14001180,0,11901180.0,0.18

In [61]:
df.isnull().sum()/len(df)

ID           0.000000
Name         0.222222
Industry     0.333333
Inception    0.111111
Revenue      0.000000
Expenses     0.000000
Profit       0.000000
Growth       0.444444
dtype: float64

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         9 non-null      float64
 1   Name       7 non-null      object
 2   Industry   6 non-null      object
 3   Inception  8 non-null      float64
 4   Revenue    9 non-null      int64
 5   Expenses   9 non-null      int64
 6   Profit     9 non-null      float64
 7   Growth     5 non-null      float64
dtypes: float64(4), int64(2), object(2)
memory usage: 648.0+ bytes

In [63]:
df.isnull().sum()

ID           0
Name         2
Industry     3
Inception    1
Revenue      0
Expenses     0
Profit       0
Growth       4
dtype: int64

In [64]:
df.select_dtypes(['object'])

              Name            Industry
0          Lamtone         IT Services
1        Stripfind  Financial Services
2  Canecorporation              Health
3              NaN         IT Services
4              NaN                 NaN
5         Techline              Health
6          Cityace                 NaN
7   Kayelectronics                 NaN
8          Ganzlax         IT Services

In [67]:
df[['Name','Industry']]=df[['Name','Industry']].fillna('unknow')

In [68]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,11757018,6482465,5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,12329371,916455,11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,10597009,0,3005820.0,NaN
3,4.0,unknow,IT Services,2013.0,0,7429377,6597557.0,NaN
4,5.0,unknow,unknow,NaN,0,7435363,3138627.0,NaN
5,6.0,Techline,Health,2006.0,0,5470303,8427816.0,0.23
6,7.0,Cityace,unknow,2010.0,9254614,0,3005116.0,0.06
7,8.0,Kayelectronics,unknow,2009.0,9451943,3878113,5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,14001180,0,11901180.0,0.18

C:\Users\Dell\AppData\Local\Temp\ipykernel_21208\2607423170.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Revenue'].replace(0,np.nan,inplace=True)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,11757018.0,6482465.0,5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,12329371.0,916455.0,11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,10597009.0,NaN,3005820.0,NaN
3,4.0,unknow,IT Services,2013.0,NaN,7429377.0,6597557.0,NaN
4,5.0,unknow,unknow,NaN,NaN,7435363.0,3138627.0,NaN
5,6.0,Techline,Health,2006.0,NaN,5470303.0,8427816.0,0.23
6,7.0,Cityace,unknow,2010.0,9254614.0,NaN,3005116.0,0.06
7,8.0,Kayelectronics,unknow,2009.0,9451943.0,3878113.0,5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,14001180.0,NaN,11901180.0,0.18

In [87]:
df['Revenue'] = pd.to_numeric(df['Revenue'], errors='coerce')
df['Revenue'] = df['Revenue'].replace(0, np.nan)

In [94]:
import numpy as np
df['Expenses']=pd.to_numeric(df['Expenses'],errors='coerce')

df['Expenses'].replace(0,np.nan,inplace=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_21208\424307526.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Expenses'].replace(0,np.nan,inplace=True)

In [96]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,11757018.0,6482465.0,5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,12329371.0,916455.0,11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,10597009.0,NaN,3005820.0,NaN
3,4.0,unknow,IT Services,2013.0,NaN,7429377.0,6597557.0,NaN
4,5.0,unknow,unknow,NaN,NaN,7435363.0,3138627.0,NaN
5,6.0,Techline,Health,2006.0,NaN,5470303.0,8427816.0,0.23
6,7.0,Cityace,unknow,2010.0,9254614.0,NaN,3005116.0,0.06
7,8.0,Kayelectronics,unknow,2009.0,9451943.0,3878113.0,5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,14001180.0,NaN,11901180.0,0.18

In [97]:
df['Industry'].value_counts()

Industry
IT Services           3
unknow                3
Health                2
Financial Services    1
Name: count, dtype: int64

In [98]:
df['Inception'].value_counts()

Inception
2009.0    2
2010.0    2
2012.0    1
2013.0    1
2006.0    1
2011.0    1
Name: count, dtype: int64

In [99]:
df['Inception'].fillna(df['Inception'].mode()[0])

0    2009.0
1    2010.0
2    2012.0
3    2013.0
4    2009.0
5    2006.0
6    2010.0
7    2009.0
8    2011.0
Name: Inception, dtype: float64

In [100]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,11757018.0,6482465.0,5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,12329371.0,916455.0,11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,10597009.0,NaN,3005820.0,NaN
3,4.0,unknow,IT Services,2013.0,NaN,7429377.0,6597557.0,NaN
4,5.0,unknow,unknow,NaN,NaN,7435363.0,3138627.0,NaN
5,6.0,Techline,Health,2006.0,NaN,5470303.0,8427816.0,0.23
6,7.0,Cityace,unknow,2010.0,9254614.0,NaN,3005116.0,0.06
7,8.0,Kayelectronics,unknow,2009.0,9451943.0,3878113.0,5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,14001180.0,NaN,11901180.0,0.18

In [101]:
df['Inception'].fillna(df['Inception'].mode()[0])

0    2009.0
1    2010.0
2    2012.0
3    2013.0
4    2009.0
5    2006.0
6    2010.0
7    2009.0
8    2011.0
Name: Inception, dtype: float64

In [102]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,11757018.0,6482465.0,5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,12329371.0,916455.0,11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,10597009.0,NaN,3005820.0,NaN
3,4.0,unknow,IT Services,2013.0,NaN,7429377.0,6597557.0,NaN
4,5.0,unknow,unknow,NaN,NaN,7435363.0,3138627.0,NaN
5,6.0,Techline,Health,2006.0,NaN,5470303.0,8427816.0,0.23
6,7.0,Cityace,unknow,2010.0,9254614.0,NaN,3005116.0,0.06
7,8.0,Kayelectronics,unknow,2009.0,9451943.0,3878113.0,5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,14001180.0,NaN,11901180.0,0.18

In [104]:
df['Revenue'].fillna(df['Expenses']+df['Profit'],inplace=True)

In [105]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,11757018.0,6482465.0,5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,12329371.0,916455.0,11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,10597009.0,NaN,3005820.0,NaN
3,4.0,unknow,IT Services,2013.0,14026934.0,7429377.0,6597557.0,NaN
4,5.0,unknow,unknow,NaN,10573990.0,7435363.0,3138627.0,NaN
5,6.0,Techline,Health,2006.0,13898119.0,5470303.0,8427816.0,0.23
6,7.0,Cityace,unknow,2010.0,9254614.0,NaN,3005116.0,0.06
7,8.0,Kayelectronics,unknow,2009.0,9451943.0,3878113.0,5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,14001180.0,NaN,11901180.0,0.18

In [106]:
df['Expenses'].fillna(df['Revenue']-df['Profit'],inplace=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_21208\1671768974.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Expenses'].fillna(df['Revenue']-df['Profit'],inplace=True)

In [107]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,11757018.0,6482465.0,5274553.0,0.30
1,2.0,Stripfind,Financial Services,2010.0,12329371.0,916455.0,11412916.0,NaN
2,3.0,Canecorporation,Health,2012.0,10597009.0,7591189.0,3005820.0,NaN
3,4.0,unknow,IT Services,2013.0,14026934.0,7429377.0,6597557.0,NaN
4,5.0,unknow,unknow,NaN,10573990.0,7435363.0,3138627.0,NaN
5,6.0,Techline,Health,2006.0,13898119.0,5470303.0,8427816.0,0.23
6,7.0,Cityace,unknow,2010.0,9254614.0,6249498.0,3005116.0,0.06
7,8.0,Kayelectronics,unknow,2009.0,9451943.0,3878113.0,5573830.0,0.04
8,9.0,Ganzlax,IT Services,2011.0,14001180.0,2100000.0,11901180.0,0.18

In [108]:
s=df['Growth']

In [109]:
s

0    0.30
1     NaN
2     NaN
3     NaN
4     NaN
5    0.23
6    0.06
7    0.04
8    0.18
Name: Growth, dtype: float64

In [ ]:
s.plot.box()

# s.boxplot()

AttributeError: 'Series' object has no attribute 'boxplot'

In [115]:
df['Growth'].fillna(df['Growth'].mean(),inplace=True)

In [116]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,11757018.0,6482465.0,5274553.0,0.300
1,2.0,Stripfind,Financial Services,2010.0,12329371.0,916455.0,11412916.0,0.162
2,3.0,Canecorporation,Health,2012.0,10597009.0,7591189.0,3005820.0,0.162
3,4.0,unknow,IT Services,2013.0,14026934.0,7429377.0,6597557.0,0.162
4,5.0,unknow,unknow,NaN,10573990.0,7435363.0,3138627.0,0.162
5,6.0,Techline,Health,2006.0,13898119.0,5470303.0,8427816.0,0.230
6,7.0,Cityace,unknow,2010.0,9254614.0,6249498.0,3005116.0,0.060
7,8.0,Kayelectronics,unknow,2009.0,9451943.0,3878113.0,5573830.0,0.040
8,9.0,Ganzlax,IT Services,2011.0,14001180.0,2100000.0,11901180.0,0.180