In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

cdfgf

In [2]:
df=pd.read_csv(r"C:\Users\Dell\Downloads\samsung_global_sales_dataset.csv")
df

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,SAMS-00000001,2021-01-01,2021,Q1,January,Argentina,South America,Buenos Aires,Samsung Galaxy Tab S9 Ultra,Galaxy Tab,...,ARS,907.0,1.130820e+06,E-commerce Platform,Samsung Pay,Business,45–54,NaN,3.2,Kept
1,SAMS-00000002,2021-03-23,2021,Q1,March,Argentina,South America,Buenos Aires,Samsung Galaxy S23,Galaxy S,...,ARS,907.0,1.322152e+06,Authorized Reseller,Net Banking,Government,55+,Feature Phone,NaN,Kept
2,SAMS-00000003,2021-05-22,2021,Q2,May,Argentina,South America,Buenos Aires,Samsung Galaxy A34 5G,Galaxy A,...,ARS,907.0,1.964399e+06,Corporate / B2B,Gift Card,Individual,25–34,New User,3.5,Kept
3,SAMS-00000004,2021-07-26,2021,Q3,July,Argentina,South America,Buenos Aires,Samsung T55 27-inch FHD,Monitor,...,ARS,907.0,6.603595e+05,Third-Party Retailer,BNPL (Buy Now Pay Later),Enterprise,55+,NaN,4.0,Kept
4,SAMS-00000005,2021-09-02,2021,Q3,September,Argentina,South America,Buenos Aires,Samsung Galaxy Z Fold 4,Galaxy Z,...,ARS,907.0,2.835246e+06,Authorized Reseller,Gift Card,Business,55+,Android (Other),3.0,Kept
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15495,SAMS-00015496,2024-08-08,2024,Q3,August,Vietnam,Asia,Nha Trang,Samsung Galaxy A54 5G,Galaxy A,...,VND,24500.0,1.168332e+07,Samsung Store,BNPL (Buy Now Pay Later),Government,25–34,Android (Samsung),4.0,Kept
15496,SAMS-00015497,2024-08-10,2024,Q3,August,Vietnam,Asia,Nha Trang,Samsung Neo QLED 8K QN900C,Smart TV,...,VND,24500.0,3.520981e+08,Carrier Store,EMI / Installment,Government,55+,NaN,NaN,Returned
15497,SAMS-00015498,2024-09-15,2024,Q3,September,Vietnam,Asia,Nha Trang,Samsung Galaxy Watch 6,Galaxy Watch,...,VND,24500.0,1.373323e+07,Online (Samsung.com),Credit Card,Enterprise,45–54,NaN,NaN,Kept
15498,SAMS-00015499,2024-09-16,2024,Q3,September,Vietnam,Asia,Nha Trang,Samsung 25L Microwave,Appliances,...,VND,24500.0,3.982720e+06,Third-Party Retailer,Debit Card,Business,18–24,NaN,3.3,Kept
15499,SAMS-00015500,2024-10-09,2024,Q4,October,Vietnam,Asia,Nha Trang,Samsung Galaxy S21 FE,Galaxy S,...,VND,24500.0,3.474712e+07,Authorized Reseller,Samsung Pay,Business,35–44,iOS,4.9,Kept

In [3]:
df.head()

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,SAMS-00000001,2021-01-01,2021,Q1,January,Argentina,South America,Buenos Aires,Samsung Galaxy Tab S9 Ultra,Galaxy Tab,...,ARS,907.0,1130820.39,E-commerce Platform,Samsung Pay,Business,45–54,NaN,3.2,Kept
1,SAMS-00000002,2021-03-23,2021,Q1,March,Argentina,South America,Buenos Aires,Samsung Galaxy S23,Galaxy S,...,ARS,907.0,1322152.04,Authorized Reseller,Net Banking,Government,55+,Feature Phone,NaN,Kept
2,SAMS-00000003,2021-05-22,2021,Q2,May,Argentina,South America,Buenos Aires,Samsung Galaxy A34 5G,Galaxy A,...,ARS,907.0,1964398.74,Corporate / B2B,Gift Card,Individual,25–34,New User,3.5,Kept
3,SAMS-00000004,2021-07-26,2021,Q3,July,Argentina,South America,Buenos Aires,Samsung T55 27-inch FHD,Monitor,...,ARS,907.0,660359.49,Third-Party Retailer,BNPL (Buy Now Pay Later),Enterprise,55+,NaN,4.0,Kept
4,SAMS-00000005,2021-09-02,2021,Q3,September,Argentina,South America,Buenos Aires,Samsung Galaxy Z Fold 4,Galaxy Z,...,ARS,907.0,2835245.72,Authorized Reseller,Gift Card,Business,55+,Android (Other),3.0,Kept

In [4]:
df.shape

(15500, 28)

In [6]:
df.columns

Index(['sale_id', 'sale_date', 'year', 'quarter', 'month', 'country', 'region',
       'city', 'product_name', 'category', 'storage', 'color', 'is_5g',
       'unit_price_usd', 'discount_pct', 'units_sold', 'discounted_price_usd',
       'revenue_usd', 'currency', 'fx_rate_to_usd', 'revenue_local_currency',
       'sales_channel', 'payment_method', 'customer_segment',
       'customer_age_group', 'previous_device_os', 'customer_rating',
       'return_status'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15500 entries, 0 to 15499
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sale_id                 15500 non-null  object
 1   sale_date               15500 non-null  object
 2   year                    15500 non-null  int64
 3   quarter                 15500 non-null  object
 4   month                   15500 non-null  object
 5   country                 15500 non-null  object
 6   region                  15500 non-null  object
 7   city                    15500 non-null  object
 8   product_name            15500 non-null  object
 9   category                15500 non-null  object
 10  storage                 7651 non-null   object
 11  color                   15500 non-null  object
 12  is_5g                   15500 non-null  object
 13  unit_price_usd          15500 non-null  float64
 14  discount_pct            15500 non-null  int64
 15  units_sold              15500 non-null  int64
 16  discounted_price_usd    15500 non-null  float64
 17  revenue_usd             15500 non-null  float64
 18  currency                15500 non-null  object
 19  fx_rate_to_usd          15500 non-null  float64
 20  revenue_local_currency  15500 non-null  float64
 21  sales_channel           15500 non-null  object
 22  payment_method          15500 non-null  object
 23  customer_segment        15500 non-null  object
 24  customer_age_group      15500 non-null  object
 25  previous_device_os      6127 non-null   object
 26  customer_rating         11249 non-null  float64
 27  return_status           15500 non-null  object
dtypes: float64(6), int64(3), object(19)
memory usage: 3.3+ MB

In [8]:
df.isnull().sum()

sale_id                      0
sale_date                    0
year                         0
quarter                      0
month                        0
country                      0
region                       0
city                         0
product_name                 0
category                     0
storage                   7849
color                        0
is_5g                        0
unit_price_usd               0
discount_pct                 0
units_sold                   0
discounted_price_usd         0
revenue_usd                  0
currency                     0
fx_rate_to_usd               0
revenue_local_currency       0
sales_channel                0
payment_method               0
customer_segment             0
customer_age_group           0
previous_device_os        9373
customer_rating           4251
return_status                0
dtype: int64

In [9]:
df

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,SAMS-00000001,2021-01-01,2021,Q1,January,Argentina,South America,Buenos Aires,Samsung Galaxy Tab S9 Ultra,Galaxy Tab,...,ARS,907.0,1.130820e+06,E-commerce Platform,Samsung Pay,Business,45–54,NaN,3.2,Kept
1,SAMS-00000002,2021-03-23,2021,Q1,March,Argentina,South America,Buenos Aires,Samsung Galaxy S23,Galaxy S,...,ARS,907.0,1.322152e+06,Authorized Reseller,Net Banking,Government,55+,Feature Phone,NaN,Kept
2,SAMS-00000003,2021-05-22,2021,Q2,May,Argentina,South America,Buenos Aires,Samsung Galaxy A34 5G,Galaxy A,...,ARS,907.0,1.964399e+06,Corporate / B2B,Gift Card,Individual,25–34,New User,3.5,Kept
3,SAMS-00000004,2021-07-26,2021,Q3,July,Argentina,South America,Buenos Aires,Samsung T55 27-inch FHD,Monitor,...,ARS,907.0,6.603595e+05,Third-Party Retailer,BNPL (Buy Now Pay Later),Enterprise,55+,NaN,4.0,Kept
4,SAMS-00000005,2021-09-02,2021,Q3,September,Argentina,South America,Buenos Aires,Samsung Galaxy Z Fold 4,Galaxy Z,...,ARS,907.0,2.835246e+06,Authorized Reseller,Gift Card,Business,55+,Android (Other),3.0,Kept
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15495,SAMS-00015496,2024-08-08,2024,Q3,August,Vietnam,Asia,Nha Trang,Samsung Galaxy A54 5G,Galaxy A,...,VND,24500.0,1.168332e+07,Samsung Store,BNPL (Buy Now Pay Later),Government,25–34,Android (Samsung),4.0,Kept
15496,SAMS-00015497,2024-08-10,2024,Q3,August,Vietnam,Asia,Nha Trang,Samsung Neo QLED 8K QN900C,Smart TV,...,VND,24500.0,3.520981e+08,Carrier Store,EMI / Installment,Government,55+,NaN,NaN,Returned
15497,SAMS-00015498,2024-09-15,2024,Q3,September,Vietnam,Asia,Nha Trang,Samsung Galaxy Watch 6,Galaxy Watch,...,VND,24500.0,1.373323e+07,Online (Samsung.com),Credit Card,Enterprise,45–54,NaN,NaN,Kept
15498,SAMS-00015499,2024-09-16,2024,Q3,September,Vietnam,Asia,Nha Trang,Samsung 25L Microwave,Appliances,...,VND,24500.0,3.982720e+06,Third-Party Retailer,Debit Card,Business,18–24,NaN,3.3,Kept
15499,SAMS-00015500,2024-10-09,2024,Q4,October,Vietnam,Asia,Nha Trang,Samsung Galaxy S21 FE,Galaxy S,...,VND,24500.0,3.474712e+07,Authorized Reseller,Samsung Pay,Business,35–44,iOS,4.9,Kept

In [11]:
df['category'].value_counts()

category
Galaxy S        2316
Accessories     2101
Galaxy A        1892
Galaxy Tab      1524
Galaxy Watch    1486
Smart TV        1295
Galaxy Z        1058
Appliances      1052
Monitor         1046
Galaxy Buds      869
Galaxy M         861
Name: count, dtype: int64

In [16]:
df.groupby('category')['storage'].apply(lambda x:x.notnull().sum())

category
Accessories        0
Appliances         0
Galaxy A        1892
Galaxy Buds        0
Galaxy M         861
Galaxy S        2316
Galaxy Tab      1524
Galaxy Watch       0
Galaxy Z        1058
Monitor            0
Smart TV           0
Name: storage, dtype: int64

In [17]:
df['sale_date']=pd.to_datetime(df['sale_date'])

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15500 entries, 0 to 15499
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sale_id                 15500 non-null  object
 1   sale_date               15500 non-null  datetime64[ns]
 2   year                    15500 non-null  int64
 3   quarter                 15500 non-null  object
 4   month                   15500 non-null  object
 5   country                 15500 non-null  object
 6   region                  15500 non-null  object
 7   city                    15500 non-null  object
 8   product_name            15500 non-null  object
 9   category                15500 non-null  object
 10  storage                 7651 non-null   object
 11  color                   15500 non-null  object
 12  is_5g                   15500 non-null  object
 13  unit_price_usd          15500 non-null  float64
 14  discount_pct            15500 non-null  int64
 15  units_sold              15500 non-null  int64
 16  discounted_price_usd    15500 non-null  float64
 17  revenue_usd             15500 non-null  float64
 18  currency                15500 non-null  object
 19  fx_rate_to_usd          15500 non-null  float64
 20  revenue_local_currency  15500 non-null  float64
 21  sales_channel           15500 non-null  object
 22  payment_method          15500 non-null  object
 23  customer_segment        15500 non-null  object
 24  customer_age_group      15500 non-null  object
 25  previous_device_os      6127 non-null   object
 26  customer_rating         11249 non-null  float64
 27  return_status           15500 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(3), object(18)
memory usage: 3.3+ MB

In [19]:
df['month_number']=df['sale_date'].dt.month

In [20]:
df['day_name']=df['sale_date'].dt.day_name()

In [21]:
df.head()

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,...,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status,month_number,day_name
0,SAMS-00000001,2021-01-01,2021,Q1,January,Argentina,South America,Buenos Aires,Samsung Galaxy Tab S9 Ultra,Galaxy Tab,...,1130820.39,E-commerce Platform,Samsung Pay,Business,45–54,NaN,3.2,Kept,1,Friday
1,SAMS-00000002,2021-03-23,2021,Q1,March,Argentina,South America,Buenos Aires,Samsung Galaxy S23,Galaxy S,...,1322152.04,Authorized Reseller,Net Banking,Government,55+,Feature Phone,NaN,Kept,3,Tuesday
2,SAMS-00000003,2021-05-22,2021,Q2,May,Argentina,South America,Buenos Aires,Samsung Galaxy A34 5G,Galaxy A,...,1964398.74,Corporate / B2B,Gift Card,Individual,25–34,New User,3.5,Kept,5,Saturday
3,SAMS-00000004,2021-07-26,2021,Q3,July,Argentina,South America,Buenos Aires,Samsung T55 27-inch FHD,Monitor,...,660359.49,Third-Party Retailer,BNPL (Buy Now Pay Later),Enterprise,55+,NaN,4.0,Kept,7,Monday
4,SAMS-00000005,2021-09-02,2021,Q3,September,Argentina,South America,Buenos Aires,Samsung Galaxy Z Fold 4,Galaxy Z,...,2835245.72,Authorized Reseller,Gift Card,Business,55+,Android (Other),3.0,Kept,9,Thursday

In [22]:
df['price_drop']=df['unit_price_usd']-df['discounted_price_usd']

In [ ]:
df['return_flag']=df['return_status'].apply(lambda x:1 if x=='')